### PR TITLE
fix(request): invalid status line return 400

### PR DESCRIPTION
**Pull request by zlayine**

### CODE REVIEW

**Comment by estarossa0** [comment]
is that code to so  get delete post don't work but only uppercased GET POST DELETE ?

**Comment by zlayine** [comment]
> is that code to so get delete post don't work but only uppercased GET POST DELETE ?

yes, method must be uppercased to pass

**Comment by estarossa0** [comment]
@ombhd is that the case for parser as well

**Review by estarossa0 — APPROVED** [review]

**Review by ombhd — CHANGES_REQUESTED** [review]
use isSet() instead of isStrUpperCase()

**Comment by zlayine** [comment]
> @ombhd is that the case for parser as well



> use isSet() instead of isStrUpperCase()

done! ty

**Comment by ombhd** [comment]
> @ombhd is that the case for parser as well

yep, but you can test

**Review by ombhd — APPROVED** [review]

**Pull request merged**
